In [1]:
import numpy as np 
x = np.zeros((3, 5, 2))
print(x.ndim)
print(x.shape)
print(x.dtype)

3
(3, 5, 2)
float64


In [4]:
x = np.array([[1, 2], [3, 4]])
print(x)

[[1 2]
 [3 4]]


In [5]:
x = np.zeros((2, 3, 2))
print(x)

[[[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]]


In [6]:
x = np.zeros(2)
print(x)
x = np.ones((2, 3))
print(x)

[0. 0.]
[[1. 1. 1.]
 [1. 1. 1.]]


In [7]:
x = np.full((2, 3) , 7)
print(x)

[[7 7 7]
 [7 7 7]]


In [8]:
x = np.arange(5)
print(x)

[0 1 2 3 4]


In [9]:
y = np.copy(x)
print(y)
y = np.zeros_like(x)
print(y)
y = np.ones_like(x)
print(y)

[0 1 2 3 4]
[0 0 0 0 0]
[1 1 1 1 1]


### slicing

In [11]:
x = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])
print(x[1, 2])              
print(x[1][2])

6
6


In [12]:
print(x[0:2, 1:3])

[[2 3]
 [5 6]]


In [13]:
print(x[::2, 2:0:-1])

[[3 2]
 [9 8]]


In [14]:
print(x[:2])

[[1 2 3]
 [4 5 6]]


### reshape  transpose

In [18]:
x = np.array([[[1, 2],[3,4],
               [5, 6],[7,8]]])
y = np.reshape(x, (2, 4))
print(y)               

[[1 2 3 4]
 [5 6 7 8]]


In [20]:
x = np.array([[1, 2, 3],[4, 5, 6]])
print(x)
print(np.transpose(x))

[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]


### element-wise

In [26]:
y = np.array([[1,2],[3,4]]) + np.array([[1,2],[3,4]])
print(y)
y = np.array([[1,2],[3,4]]) * np.array([[1,2],[3,4]])
print(y)
y = np.array([[1,3],[4,4]]) > np.array([[1,2],[3,4]])
print(y)

[[2 4]
 [6 8]]
[[ 1  4]
 [ 9 16]]
[[False  True]
 [ True False]]


### broadcasting

In [28]:
y = np.array([[1,2],[3,4]]) + np.array([[1,2]])
print(y)

[[2 4]
 [4 6]]


In [3]:
y = np.array([[1],[3]]) + np.array([3,4])
print(y)

[[4 5]
 [6 7]]


### 透過tuple list 取值

In [4]:
x = np.array([0,1,2,3,4])
idx = [1, 3]
x[idx] = 7 
print(x)

[0 7 2 7 4]


In [6]:
x[idx] = (8,9)
print(x)

[0 8 2 9 4]


In [7]:
y = x[idx]
print(y)

[8 9]


In [8]:
print(y[[1,0,1]])

[9 8 9]


In [10]:
x = np.array([0,1,2])
idx = np.array([True,False,True])
print(x[idx])
x[idx] = 7 
print(x)

[0 2]
[7 1 7]


### 延著陣列某一軸進行運算

In [11]:
a = np.array([[1,2],
              [3,4]])
np.max(a)              

4

In [12]:
print(np.max(a, axis=0))
print(np.max(a, axis=1))

[3 4]
[2 4]


In [18]:
a = np.array([[[1,2],
               [3,4]],
              [[1,2],
               [3,4]]])              

In [19]:
print(np.max(a, axis=0))
print(np.max(a, axis=1))
print(np.max(a, axis=2))

[[1 2]
 [3 4]]
[[3 4]
 [3 4]]
[[2 4]
 [2 4]]


### dot product 點積運算

In [20]:
##1D
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])
np.dot(x, y)

32

In [5]:
##2D
x = np.array([[1, 2],
              [3, 4],
              [5, 6]])
y = np.array([[1, 2, 3],
              [4, 5, 6]])
np.dot(x, y)                            

array([[ 9, 12, 15],
       [19, 26, 33],
       [29, 40, 51]])

In [7]:
x = np.array([[1, 2, 3],
              [4, 5, 6]])
y = np.array([1, 2, 3])
np.dot(x, y)                            

array([14, 32])

In [9]:
x = np.array([1, 2])
y = np.array([[4, 5, 6],
              [7, 8, 9]])
print(x.shape)              
print(y.shape)              
print(np.dot(x, y))            

(2,)
(2, 3)
[18 21 24]
