In [2]:
import numpy as np 

np.arange(9)

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [4]:
arr1 = np.arange(9).reshape(3, 3)
arr1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [6]:
arr1[0, :]  

array([0, 1, 2])

In [7]:
arr1[:, 0]

array([0, 3, 6])

In [9]:
arr2 = np.arange(9, 18).reshape(3, 3)
arr2

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [10]:
np.dot(arr1, arr2)

array([[ 42,  45,  48],
       [150, 162, 174],
       [258, 279, 300]])

In [11]:
arr1 * arr2

array([[  0,  10,  22],
       [ 36,  52,  70],
       [ 90, 112, 136]])

In [12]:
np.zeros((2, 3), dtype=np.int64)

array([[0, 0, 0],
       [0, 0, 0]], dtype=int64)

In [14]:
np.ones((2, 3), dtype=np.float64)

array([[1., 1., 1.],
       [1., 1., 1.]])