In [3]:
import numpy as np 
import scipy.linalg as linalg 
from scipy.optimize import minimize_scalar

In [9]:
matrix = np.array([[1, -1, -1], [-1, 1, -1], [-1, -1, 1]])
print("行列式:" + str(linalg.det(matrix)))
print("反矩陣:")
print(str(linalg.inv(matrix)))

行列式:-4.0
反矩陣:
[[ 0.  -0.5 -0.5]
 [-0.5 -0.  -0.5]
 [-0.5 -0.5  0. ]]


In [12]:
## 原 矩陣與反矩陣的乘積，應為單位矩陣
matrix.dot(linalg.inv(matrix))

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [16]:
eig_value, eig_vector = linalg.eig(matrix)
print("特徵值:",eig_value)
print("特徵向量:",eig_vector)

特徵值: [-1.+0.j  2.+0.j  2.+0.j]
特徵向量: [[ 0.57735027 -0.81649658  0.42755853]
 [ 0.57735027  0.40824829 -0.81618716]
 [ 0.57735027  0.40824829  0.38862863]]
