In [14]:
import numpy as np 

a = np.arange(12)
print(a)
print('================')
print(a.reshape(3, 4))
b = np.reshape(a, (3, 4))
print(b)
print('================')

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [20]:
# 透過-1 模糊設定
print(a.reshape(3, -1))
print(a.reshape(-1, 6))

[[ 0  0  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  0  2  3  4  5]
 [ 6  7  8  9 10 11]]


In [19]:
# 重塑後的陣列修改後 若改變元素值，也將影響原重塑前的陣列
b[0, 1] = 0
print(a)
print(b)

[ 0  0  2  3  4  5  6  7  8  9 10 11]
[[ 0  0  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [21]:
a = np.arange(12).reshape(3, 4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [22]:
b = np.arange(12).reshape(3, -1)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [25]:
c = np.arange(15).reshape(3, 4)
c

ValueError: cannot reshape array of size 15 into shape (3,4)