In [6]:
import numpy as np

a = np.arange(12)
print(np.reshape(a, (3, 4)))
print(np.resize(a, (3, 5)))
print(np.resize(a, (3, 2)))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11  0  1  2]]
[[0 1]
 [2 3]
 [4 5]]


In [3]:
np.resize(a, (3, 5))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11,  0,  1,  2]])

## np.resize() 建立不同物件

In [10]:
b = np.resize(a, (3, 4))
b[0, 1] = 0
print(b)
print(a)

[[ 0  0  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[ 0  1  2  3  4  5  6  7  8  9 10 11]
