## append()  不指定軸 將轉換為1D陣列

In [5]:
import numpy as np 

a = np.arange(12)
np.append(a , [6, 4, 2])

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11,  6,  4,  2])

In [4]:
b = np.arange(12).reshape(3, 4)
print(b)
np.append(b , [1, 2, 3, 4])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11,  1,  2,  3,  4])

In [6]:
print(b)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


## append()  指定軸

In [8]:
np.append(b, [[12, 13, 14, 15]], axis=0)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [9]:
np.append(b, [12, 13, 14, 15], axis=0)

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

In [15]:
c = np.arange(12).reshape(3, 4)
print(c)
print(c.shape)

d = np.linspace(0, 26, 12).reshape(3, 4)
print(d)
print(d.shape)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
(3, 4)
[[ 0.          2.36363636  4.72727273  7.09090909]
 [ 9.45454545 11.81818182 14.18181818 16.54545455]
 [18.90909091 21.27272727 23.63636364 26.        ]]
(3, 4)


In [17]:
print(np.append(c,d,axis=0))
print(np.append(c,d,axis=0).shape)

[[ 0.          1.          2.          3.        ]
 [ 4.          5.          6.          7.        ]
 [ 8.          9.         10.         11.        ]
 [ 0.          2.36363636  4.72727273  7.09090909]
 [ 9.45454545 11.81818182 14.18181818 16.54545455]
 [18.90909091 21.27272727 23.63636364 26.        ]]
(6, 4)


In [18]:
print(np.append(c,d,axis=1))
print(np.append(c,d,axis=1).shape)

[[ 0.          1.          2.          3.          0.          2.36363636
   4.72727273  7.09090909]
 [ 4.          5.          6.          7.          9.45454545 11.81818182
  14.18181818 16.54545455]
 [ 8.          9.         10.         11.         18.90909091 21.27272727
  23.63636364 26.        ]]
(3, 8)
