In [2]:
import numpy as np 
np.random.rand()

0.7139128251354363

In [3]:
np.random.randint(10)

5

In [4]:
np.random.rand(2,3)

array([[0.46177564, 0.9292045 , 0.77551853],
       [0.6214693 , 0.66737519, 0.71583417]])

In [5]:
np.random.randint(10, size=(2, 3))

array([[0, 2, 4],
       [5, 5, 0]])

In [6]:
np.random.randint(5, 10, size=10)

array([6, 6, 6, 9, 8, 9, 8, 8, 8, 8])

In [10]:
a = np.random.rand(10)
b = (10-5) * a + 5
print('np.random.rand(10)',a)
print('(10-5) * np.random.rand(10)+ 5',b)

np.random.rand(10) [0.22991791 0.41478316 0.81061236 0.75174121 0.47767352 0.58634797
 0.87237428 0.54626045 0.47275147 0.60265608]
(10-5) * np.random.rand(10)+ 5 [6.14958956 7.07391581 9.05306182 8.75870607 7.38836762 7.93173985
 9.36187141 7.73130226 7.36375736 8.01328042]


## np.random.seed()

In [21]:
np.random.seed(seed=21)
print(np.random.rand())
np.random.seed(seed=21)
print(np.random.rand())
np.random.seed(seed=211)
print(np.random.rand())
np.random.seed(seed=211)
print(np.random.rand())
np.random.seed(seed=21)
print(np.random.rand())

0.04872488080912729
0.04872488080912729
0.7813680777780895
0.7813680777780895
0.04872488080912729


## np.random.choice()

In [32]:
a = ['Python', 'Ruby', 'Java', 'PHP', 'JavaScript']
print(np.random.choice(a, 3))
print(np.random.choice(a, 5, replace=True))
print(np.random.choice(a, 5, replace=False))

['Java' 'Java' 'Python']
['JavaScript' 'Java' 'Python' 'Python' 'Java']
['Java' 'Ruby' 'JavaScript' 'Python' 'PHP']


In [36]:
print(np.random.choice(a, 20, p= [0.8, 0.05, 0.05, 0.05, 0.05]))

['Ruby' 'Java' 'Python' 'Java' 'Python' 'Python' 'Python' 'Ruby' 'Python'
 'Python' 'Python' 'Python' 'Java' 'Python' 'Ruby' 'Python' 'Python'
 'Python' 'Ruby' 'Python']


In [38]:
print(np.random.choice(5, 10))

[2 2 1 1 3 1 1 1 1 1]


## np.random.shuffle()

In [40]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [42]:
np.random.shuffle(a)
a

array([4, 3, 5, 6, 0, 1, 7, 8, 9, 2])