In [56]:
import numpy as np 
a = np.random.randint(10, size=(2, 3))
a

array([[7, 3, 9],
       [6, 3, 8]])

In [57]:
print(np.any(a == 9))
print(np.any(a == 5))

True
False


In [59]:
print(np.any(a%2==0,axis=0))
print(np.any(a%2==1,axis=0))
print(np.any(a%2==0,axis=1))
print(np.any(a%2==1,axis=1))

[ True False  True]
[ True  True  True]
[False  True]
[ True  True]


In [60]:
print(np.any(a%2==0,axis=0,keepdims=True))
print(np.any(a%2==1,axis=0,keepdims=True))
print(np.any(a%2==0,axis=1,keepdims=True))
print(np.any(a%2==1,axis=1,keepdims=True))

[[ True False  True]]
[[ True  True  True]]
[[False]
 [ True]]
[[ True]
 [ True]]


In [62]:
print((a%5==0).any())
print((a>3).any())

False
True


In [68]:
b = np.random.randint(10, size=(2,3))
print(b)
print((a==b).any(axis=0))
print((a==b).any(axis=1))
print((a==b).any(axis=0, keepdims=True))
print((a==b).any(axis=1, keepdims=True))

[[2 1 9]
 [1 4 3]]
[False False  True]
[ True False]
[[False False  True]]
[[ True]
 [False]]
