## condition only(show index or value)

In [18]:
import numpy as np
a = np.arange(20, 0 ,-2)
print(a)
print(np.where(a<10))
print(a[np.where(a<10)])

[20 18 16 14 12 10  8  6  4  2]
(array([6, 7, 8, 9], dtype=int64),)
[8 6 4 2]


In [19]:
b = np.arange(12).reshape((3, 4))
print(b)
print(np.where(b % 2 == 0))
print(b[np.where(b % 2 == 0)])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
(array([0, 0, 1, 1, 2, 2], dtype=int64), array([0, 2, 0, 2, 0, 2], dtype=int64))
[ 0  2  4  6  8 10]


## condition with parameter (replace the value of true & false )

In [20]:
print(np.where(b % 2 == 0, 'even', 'odd'))

[['even' 'odd' 'even' 'odd']
 ['even' 'odd' 'even' 'odd']
 ['even' 'odd' 'even' 'odd']]


In [25]:
a = np.arange(12).reshape((3, 4))
b = np.reshape(a, (3, 4))
c = b ** 2
print(b)
print(c)
print(np.where(b % 2 == 0, b, c))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[  0   1   4   9]
 [ 16  25  36  49]
 [ 64  81 100 121]]
[[  0   1   2   9]
 [  4  25   6  49]
 [  8  81  10 121]]
