## np.amax()

In [2]:
import numpy as np 
print(np.amax(np.array([1, 2, 3, 4, 4])))

4


## np.amax(a,axis=)

In [3]:
arr = np.arange(12).reshape((3, 4))
print(arr)
print(np.amax(arr, axis=0))
print(np.amax(arr, axis=1))
print(np.amax(arr, axis=0, keepdims=True))
print(np.amax(arr, axis=1, keepdims=True))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[ 8  9 10 11]
[ 3  7 11]
[[ 8  9 10 11]]
[[ 3]
 [ 7]
 [11]]


## ndarray物件.max()

In [5]:
arr2 = np.random.randint(30, size=(2, 3, 5))
print(arr2)
print(arr2.max())
print(arr2.max(axis=0))
print(arr2.max(axis=1))
print(arr2.max(axis=2))

[[[26  0 20 18  8]
  [26 24  3 26  3]
  [10 23 15 22 24]]

 [[24  5  3 15 18]
  [26  2  6 26 13]
  [ 6 16  3 22 18]]]
26
[[26  5 20 18 18]
 [26 24  6 26 13]
 [10 23 15 22 24]]
[[26 24 20 26 24]
 [26 16  6 26 18]]
[[26 26 24]
 [24 26 22]]
