## np.amin()

In [2]:
import numpy as np 
print(np.amin(np.array([1, 2, 3, 4, 4])))

1


## np.amax(a,axis=)

In [3]:
arr = np.arange(12).reshape((3, 4))
print(arr)
print(np.amin(arr, axis=0))
print(np.amin(arr, axis=1))
print(np.amin(arr, axis=0, keepdims=True))
print(np.amin(arr, axis=1, keepdims=True))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[0 1 2 3]
[0 4 8]
[[0 1 2 3]]
[[0]
 [4]
 [8]]


In [4]:
arr2 = np.random.randint(30, size=(2, 3, 5))
print(arr2)
print(arr2.min())
print(arr2.min(axis=0))
print(arr2.min(axis=1))
print(arr2.min(axis=2))

[[[10  7 10  9 20]
  [18  3  0 18 29]
  [11 11 15 17  8]]

 [[18 18 16  4 15]
  [22 10  6  8 23]
  [22 23 23 19 26]]]
0
[[10  7 10  4 15]
 [18  3  0  8 23]
 [11 11 15 17  8]]
[[10  3  0  9  8]
 [18 10  6  4 15]]
[[ 7  0  8]
 [ 4  6 19]]
