In [2]:
import numpy as np

a = np.random.randint(10, size=10)
print(a)
print(np.min(a))
print(np.argmin(a))
print(a.argmin())

[7 2 2 2 7 2 0 1 2 6]
0
6
6


## 2D

In [3]:
b = np.random.randint(10, size=(3, 4))
print(b)
print(np.min(b))
print(np.argmin(b))
print(b.argmin())

[[5 5 9 2]
 [4 4 4 8]
 [8 8 8 8]]
2
3
3


In [4]:
print(np.min(b, axis=0))
print(np.argmin(b, axis=0))
print(np.min(b, axis=1))
print(np.argmin(b, axis=1))

[4 4 4 2]
[1 1 1 0]
[2 4 8]
[3 0 0]


## 3D

In [5]:
c = np.random.randint(10, size=(2, 3, 4))
print(c)
print(np.min(c))
print(np.argmin(c))
print(np.min(c, axis=0))
print(np.argmin(c, axis=0))
print(np.min(c, axis=1))
print(np.argmin(c, axis=1))
print(np.min(c, axis=2))
print(np.argmin(c, axis=2))

[[[0 2 6 3]
  [0 5 4 3]
  [3 8 7 4]]

 [[9 5 9 5]
  [4 4 5 8]
  [6 9 7 3]]]
0
0
[[0 2 6 3]
 [0 4 4 3]
 [3 8 7 3]]
[[0 0 0 0]
 [0 1 0 0]
 [0 0 0 1]]
[[0 2 4 3]
 [4 4 5 3]]
[[0 0 1 0]
 [1 1 1 2]]
[[0 0 3]
 [5 4 3]]
[[0 0 0]
 [1 0 3]]
