In [7]:
import numpy as np 

a = np.arange(12).reshape(3, 4)
print(a)
print(np.transpose(a))
print(np.transpose(a, (1, 0)))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


In [13]:
b = np.arange(6)
print(b)
print(np.transpose(b))
print(b.reshape((1, 6)))
print(np.transpose(b.reshape((1, 6))))

[0 1 2 3 4 5]
[0 1 2 3 4 5]
[[0 1 2 3 4 5]]
[[0]
 [1]
 [2]
 [3]
 [4]
 [5]]


In [4]:
c = np.arange(24).reshape(4, 3, 2)
print(c)

[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]

 [[12 13]
  [14 15]
  [16 17]]

 [[18 19]
  [20 21]
  [22 23]]]


In [9]:
print(np.transpose(c,axes=(2, 1, 0)))

[[[ 0  6 12 18]
  [ 2  8 14 20]
  [ 4 10 16 22]]

 [[ 1  7 13 19]
  [ 3  9 15 21]
  [ 5 11 17 23]]]


In [10]:
print(np.transpose(c,axes=(1, 0, 2)))

[[[ 0  1]
  [ 6  7]
  [12 13]
  [18 19]]

 [[ 2  3]
  [ 8  9]
  [14 15]
  [20 21]]

 [[ 4  5]
  [10 11]
  [16 17]
  [22 23]]]


## ndarray.transpose(axes)

In [11]:
c.transpose()

array([[[ 0,  6, 12, 18],
        [ 2,  8, 14, 20],
        [ 4, 10, 16, 22]],

       [[ 1,  7, 13, 19],
        [ 3,  9, 15, 21],
        [ 5, 11, 17, 23]]])

In [12]:
c.shape

(4, 3, 2)

In [13]:
c.transpose().shape

(2, 3, 4)

In [15]:
c.transpose(1, 0, 2).shape

(3, 4, 2)

## ndarray.T

In [18]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [19]:
a.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [22]:
b

array([0, 1, 2, 3, 4, 5])

In [23]:
b.T

array([0, 1, 2, 3, 4, 5])

In [24]:
a.transpose().shape == a.T.shape

True

In [25]:
b.transpose().shape == b.T.shape

True