In [7]:
import numpy as np 

a = np.arange(12).reshape(3, 4)
print(a)
print(np.transpose(a))
print(np.transpose(a, (1, 0)))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


In [12]:
b = np.arange(6)
print(b)
print(np.transpose(b))
print(b.reshape((1, 6)))
np.transpose(b.reshape((1, 6)))

[0 1 2 3 4 5]
[0 1 2 3 4 5]
[[0 1 2 3 4 5]]


array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])