## 1D

In [2]:
import numpy as np
a = np.random.randint(0, 100, size=20)
print(a)
print(np.sort(a))
print(np.argsort(a))

[ 1 58 15 25 47 12 37 26 96 66 39 81 21 68 32 34 52 23 42 31]
[ 1 12 15 21 23 25 26 31 32 34 37 39 42 47 52 58 66 68 81 96]
[ 0  5  2 12 17  3  7 19 14 15  6 10 18  4 16  1  9 13 11  8]


## 2D

In [6]:
b = np.random.randint(0, 100, size=20).reshape(4,5)
print(b)
print(np.sort(b))
print(np.argsort(b))

[[81 77 84 81 68]
 [25 84  1 67 65]
 [31 35 94 75 96]
 [37  6  8 35  2]]
[[68 77 81 81 84]
 [ 1 25 65 67 84]
 [31 35 75 94 96]
 [ 2  6  8 35 37]]
[[4 1 0 3 2]
 [2 0 4 3 1]
 [0 1 3 2 4]
 [4 1 2 3 0]]


In [8]:
print(b)
print(np.sort(b, axis=0))
print(np.argsort(b, axis=0))

[[81 77 84 81 68]
 [25 84  1 67 65]
 [31 35 94 75 96]
 [37  6  8 35  2]]
[[25  6  1 35  2]
 [31 35  8 67 65]
 [37 77 84 75 68]
 [81 84 94 81 96]]
[[1 3 1 3 3]
 [2 2 3 1 1]
 [3 0 0 2 0]
 [0 1 2 0 2]]


## 3D

In [12]:
c = np.random.randint(0, 100, size=(2,4,5))
print(c)
print(np.sort(c,axis=0))
print(np.argsort(c,axis=0))

[[[19 37 58 99 90]
  [46 73 68 59 11]
  [16 61 19 67 65]
  [17 73 48 42 10]]

 [[17 95 48  5 17]
  [63 27 16 17 84]
  [95 52 87 12 84]
  [85 94 93 77 51]]]
[[[17 37 48  5 17]
  [46 27 16 17 11]
  [16 52 19 12 65]
  [17 73 48 42 10]]

 [[19 95 58 99 90]
  [63 73 68 59 84]
  [95 61 87 67 84]
  [85 94 93 77 51]]]
[[[1 0 1 1 1]
  [0 1 1 1 0]
  [0 1 0 1 0]
  [0 0 0 0 0]]

 [[0 1 0 0 0]
  [1 0 0 0 1]
  [1 0 1 0 1]
  [1 1 1 1 1]]]


## 建立陣列時 如有使用dtype給予欄位名稱 就可以使用sort() 指定order參數排序

In [5]:
values = [('Alice', 25, 9.7), ('Bob', 12, 7.6), ('Catherine', 1, 8.6), ('David', 10, 7.6)]
dt = [('name', 'S10'), ('ID', int), ('score', float)]
a = np.array(values, dtype=dt)
print(a)
print(np.sort(a, order='score'))
print(np.argsort(a, order='score'))
print(np.sort(a, order=['score', 'ID']))

[(b'Alice', 25, 9.7) (b'Bob', 12, 7.6) (b'Catherine',  1, 8.6)
 (b'David', 10, 7.6)]
[(b'Bob', 12, 7.6) (b'David', 10, 7.6) (b'Catherine',  1, 8.6)
 (b'Alice', 25, 9.7)]
[1 3 2 0]
[(b'David', 10, 7.6) (b'Bob', 12, 7.6) (b'Catherine',  1, 8.6)
 (b'Alice', 25, 9.7)]


## ndarary.sort()  直接改變原物件

In [9]:
a = np.random.randint(0, 100 ,20)
a

array([93, 52, 83, 65, 50, 78, 72, 40, 26, 80, 62, 36, 80, 61, 69, 80, 87,
       92, 22, 56])

In [10]:
print(a)
print(np.sort(a))
print(a)

[93 52 83 65 50 78 72 40 26 80 62 36 80 61 69 80 87 92 22 56]
[22 26 36 40 50 52 56 61 62 65 69 72 78 80 80 80 83 87 92 93]
[93 52 83 65 50 78 72 40 26 80 62 36 80 61 69 80 87 92 22 56]


In [11]:
print(a.sort())
print(a)

None
[22 26 36 40 50 52 56 61 62 65 69 72 78 80 80 80 83 87 92 93]
