In [1]:
import numpy as np 

### np.hstack()     (1)僅針對 axis=1 進行合併  (2)軸數必須相等才可合併 (3)除了第一軸可以不相等，其他軸緯度必須相同

## 1D

In [3]:
a = np.arange(12)
b = np.arange(2)
print(a)
print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[0 1]


In [6]:
np.hstack((a, b))

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11,  0,  1])

## 2D

In [11]:
c = np.arange(4).reshape((2, 2))
c

array([[0, 1],
       [2, 3]])

In [9]:
np.hstack((a, c))

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 1 dimension(s) and the array at index 1 has 2 dimension(s)

In [12]:
d = np.arange(6).reshape((2, 3))
print(d)
np.hstack((c, d))

[[0 1 2]
 [3 4 5]]


array([[0, 1, 0, 1, 2],
       [2, 3, 3, 4, 5]])

## 3D

In [17]:
e = np.arange(12).reshape((2, 2, 3))
f = np.arange(6).reshape((2, 1, 3))
print(e.shape)
print(e)
print("==========================")
print(f.shape)
print(f)

(2, 2, 3)
[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]
(2, 1, 3)
[[[0 1 2]]

 [[3 4 5]]]


In [16]:
np.hstack((e, f))

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 0,  1,  2]],

       [[ 6,  7,  8],
        [ 9, 10, 11],
        [ 3,  4,  5]]])