In [1]:
import numpy as np 

### np.vstack()     (1)僅針對 axis=0 進行合併  (2)軸數必須相等才可合併 (3)除了第一軸可以不相等，其他軸緯度必須相同

## 2D

In [5]:
a = np.arange(12).reshape((-1, 1))
b = np.arange(2).reshape((-1, 1))
print(a)
print(b)
np.vstack((a, b))

[[ 0]
 [ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]]
[[0]
 [1]]


array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [ 0],
       [ 1]])

In [9]:
c = np.arange(2).reshape((1, 2))
d = np.arange(4).reshape((2, 2))
print(c)
print("==========================")
print(d)
np.vstack((c, d))

[[0 1]]
[[0 1]
 [2 3]]


array([[0, 1],
       [0, 1],
       [2, 3]])

## 3D

In [11]:
e = np.arange(24).reshape(4, 3, 2)
f = np.arange(6).reshape((1, 3, 2))
print(e)
print("==========================")
print(f)
np.vstack((e, f))

[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]

 [[12 13]
  [14 15]
  [16 17]]

 [[18 19]
  [20 21]
  [22 23]]]
[[[0 1]
  [2 3]
  [4 5]]]


array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15],
        [16, 17]],

       [[18, 19],
        [20, 21],
        [22, 23]],

       [[ 0,  1],
        [ 2,  3],
        [ 4,  5]]])