In [2]:
import numpy as np 
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [4]:
np.ones((3, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [10]:
a = np.array([[1, 2, 3],[4, 5, 6]])
b = np.ones_like(a)
b

array([[1, 1, 1],
       [1, 1, 1]])