In [3]:
import numpy as np 
print(np.arange(5))
print(np.arange(-10))
print(np.arange(4.5))

[0 1 2 3 4]
[]
[0. 1. 2. 3. 4.]


In [7]:
print(np.arange(1, 8))
print(np.arange(2, 10))
print(np.arange(0.5, 5.5))
print(np.arange(0.55, 5.55))

[1 2 3 4 5 6 7]
[2 3 4 5 6 7 8 9]
[0.5 1.5 2.5 3.5 4.5]
[0.55 1.55 2.55 3.55 4.55]


## 設置step參數

In [12]:
print(np.arange(2, 12, 2))
print(np.arange(2, 5, 0.2))
print(np.arange(5, 2, -1))

[ 2  4  6  8 10]
[2.  2.2 2.4 2.6 2.8 3.  3.2 3.4 3.6 3.8 4.  4.2 4.4 4.6 4.8]
[5 4 3]


## 設定dtype參數

In [15]:
print(np.arange(5, dtype='float64'))
print(np.arange(5.0, dtype='int'))
print(np.arange(0, 5, 0.5, dtype='int'))
print(np.arange(0, 5, 1.5, dtype='int'))

[0. 1. 2. 3. 4.]
[0 1 2 3 4]
[0 0 0 0 0 0 0 0 0 0]
[0 1 2 3]
