In [2]:
import numpy as np 
print(np.linspace(0, 1))

[0.         0.02040816 0.04081633 0.06122449 0.08163265 0.10204082
 0.12244898 0.14285714 0.16326531 0.18367347 0.20408163 0.2244898
 0.24489796 0.26530612 0.28571429 0.30612245 0.32653061 0.34693878
 0.36734694 0.3877551  0.40816327 0.42857143 0.44897959 0.46938776
 0.48979592 0.51020408 0.53061224 0.55102041 0.57142857 0.59183673
 0.6122449  0.63265306 0.65306122 0.67346939 0.69387755 0.71428571
 0.73469388 0.75510204 0.7755102  0.79591837 0.81632653 0.83673469
 0.85714286 0.87755102 0.89795918 0.91836735 0.93877551 0.95918367
 0.97959184 1.        ]


In [5]:
print(np.linspace(0, 1, 5))
print(np.linspace(0, 2, 3))
print(np.linspace(0, -2, 3))
print(np.linspace(0, 2, num=3))

[0.   0.25 0.5  0.75 1.  ]
[0. 1. 2.]
[ 0. -1. -2.]
[0. 1. 2.]


## 設定 endpoint參數

In [9]:
print(np.linspace(0, 2, num=3, endpoint=True))
print(np.linspace(0, 2, num=3, endpoint=False))
print(np.linspace(0, 4, num=3, endpoint=False))

[0. 1. 2.]
[0.         0.66666667 1.33333333]
[0.         1.33333333 2.66666667]


In [5]:
print(np.linspace(0, 1, retstep=True))
print(np.linspace(0, 2, num=3, retstep=True))

(array([0.        , 0.02040816, 0.04081633, 0.06122449, 0.08163265,
       0.10204082, 0.12244898, 0.14285714, 0.16326531, 0.18367347,
       0.20408163, 0.2244898 , 0.24489796, 0.26530612, 0.28571429,
       0.30612245, 0.32653061, 0.34693878, 0.36734694, 0.3877551 ,
       0.40816327, 0.42857143, 0.44897959, 0.46938776, 0.48979592,
       0.51020408, 0.53061224, 0.55102041, 0.57142857, 0.59183673,
       0.6122449 , 0.63265306, 0.65306122, 0.67346939, 0.69387755,
       0.71428571, 0.73469388, 0.75510204, 0.7755102 , 0.79591837,
       0.81632653, 0.83673469, 0.85714286, 0.87755102, 0.89795918,
       0.91836735, 0.93877551, 0.95918367, 0.97959184, 1.        ]), 0.02040816326530612)
(array([0., 1., 2.]), 1.0)
