## Copy

In [9]:
import numpy as np 

a = np.arange(12).reshape((2, 6))
print(a)
b = a.flatten()
print(b)
print(b.shape)
print(a)
print(a.shape)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
[ 0  1  2  3  4  5  6  7  8  9 10 11]
(12,)
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
(2, 6)


In [8]:
c = np.arange(24).reshape((2, 3, 4))
print(c)
d = c.flatten()
print(c)
print(d)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
