## View

In [6]:
import numpy as np 
a = np.arange(10).reshape(2, 5)
print(a)
print(a.ravel())
print(np.ravel(a))

[[0 1 2 3 4]
 [5 6 7 8 9]]
[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]


In [7]:
a.ravel(order='C')

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
a.ravel(order='F')

array([0, 5, 1, 6, 2, 7, 3, 8, 4, 9])