In [2]:
import numpy as np 
a = np.random.randint(0, 10,size=20)
print(a)
print(np.nonzero(a))
print(a.nonzero())
print(a[np.nonzero(a)])

[9 5 1 9 4 4 0 7 9 3 8 2 8 4 0 7 4 2 2 4]
(array([ 0,  1,  2,  3,  4,  5,  7,  8,  9, 10, 11, 12, 13, 15, 16, 17, 18,
       19], dtype=int64),)
(array([ 0,  1,  2,  3,  4,  5,  7,  8,  9, 10, 11, 12, 13, 15, 16, 17, 18,
       19], dtype=int64),)
[9 5 1 9 4 4 7 9 3 8 2 8 4 7 4 2 2 4]


## 2D

In [7]:
b = np.random.randint(0, 10, size=(4, 5))
print(b)
print(np.nonzero(b))
print(b.nonzero())
print(b[np.nonzero(b)])

[[7 1 4 5 6]
 [9 7 3 6 6]
 [9 7 9 6 0]
 [4 1 7 1 8]]
(array([0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3, 3],
      dtype=int64), array([0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 0, 1, 2, 3, 4],
      dtype=int64))
(array([0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3, 3],
      dtype=int64), array([0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 0, 1, 2, 3, 4],
      dtype=int64))
[7 1 4 5 6 9 7 3 6 6 9 7 9 6 4 1 7 1 8]
