In [1]:
import numpy as np 
np.newaxis is None

True

In [5]:
x = np.arange(15).reshape(3, 5)
x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [6]:
print(x[np.newaxis, :, :])
print(x[np.newaxis, :, :].shape)

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]]
(1, 3, 5)


In [11]:
print(x[:, np.newaxis, :])
print(x[:, np.newaxis, :].shape)
print(x[:, None, :])
print(x[:, None, :].shape)

[[[ 0  1  2  3  4]]

 [[ 5  6  7  8  9]]

 [[10 11 12 13 14]]]
(3, 1, 5)
[[[ 0  1  2  3  4]]

 [[ 5  6  7  8  9]]

 [[10 11 12 13 14]]]
(3, 1, 5)


In [9]:
print(x[:, :, np.newaxis])
print(x[:, :, np.newaxis].shape)

[[[ 0]
  [ 1]
  [ 2]
  [ 3]
  [ 4]]

 [[ 5]
  [ 6]
  [ 7]
  [ 8]
  [ 9]]

 [[10]
  [11]
  [12]
  [13]
  [14]]]
(3, 5, 1)


## np.reshape()

In [12]:
import numpy as np 

x = np.arange(15).reshape(3, 5)
np.reshape(x, (1, 3, 5))

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]]])

In [13]:
np.reshape(x, (3, 1, 5))

array([[[ 0,  1,  2,  3,  4]],

       [[ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14]]])

In [15]:
x = x.flatten()
np.reshape(x, (-1, 1))

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14]])