In [1]:
import numpy as np  

## 合併陣列( 不 設定控制字串) = np.vstack()

In [2]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6]) 
np.r_[a, b] 

array([1, 2, 3, 4, 5, 6])

In [3]:
np.r_[2, 5, 3, np.array([2, 3]), 4.2]

array([2. , 5. , 3. , 2. , 3. , 4.2])

In [7]:
c = np.zeros((2, 3))
d = np.ones((3, 3))
np.r_[c, d]

array([[0., 0., 0.],
       [0., 0., 0.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [8]:
d = np.ones((3, 4))
np.r_[c, d]

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 3 and the array at index 1 has size 4

## 合併陣列 (設定控制字串) 2D

In [10]:
a = np.ones((2, 2))
b = np.zeros((2, 2))
print(np.r_['1', a, b])
print(np.r_['1', a, b].shape)

[[1. 1. 0. 0.]
 [1. 1. 0. 0.]]
(2, 4)


In [11]:
print(np.r_['0', a, b])
print(np.r_[a, b])
print(np.r_['0', a, b].shape)

[[1. 1.]
 [1. 1.]
 [0. 0.]
 [0. 0.]]
[[1. 1.]
 [1. 1.]
 [0. 0.]
 [0. 0.]]
(4, 2)


## 合併陣列 (設定控制字串) 3D

In [13]:
c = np.ones((2, 2, 2))
d = np.zeros((2, 2, 2))
print(c)
print(d)

[[[1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]]]
[[[0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]]]


In [14]:
np.r_[c, d]

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]]])

In [15]:
np.r_['1', c, d]

array([[[1., 1.],
        [1., 1.],
        [0., 0.],
        [0., 0.]],

       [[1., 1.],
        [1., 1.],
        [0., 0.],
        [0., 0.]]])

In [17]:
np.r_['2', c, d]

array([[[1., 1., 0., 0.],
        [1., 1., 0., 0.]],

       [[1., 1., 0., 0.],
        [1., 1., 0., 0.]]])

In [19]:
print(np.r_['0', c, d].shape)
print(np.r_['1', c, d].shape)
print(np.r_['2', c, d].shape)

(4, 2, 2)
(2, 4, 2)
(2, 2, 4)


## 改變y,z值

In [20]:
np.r_['0, 2', [0, 1, 2], [3, 3, 3]]

array([[0, 1, 2],
       [3, 3, 3]])

In [23]:
print(np.array([0, 1, 2]).shape)
print(np.array([3, 3, 3]).shape)
np.r_['0, 2', [0, 1, 2], [3, 3, 3]].shape

(3,)
(3,)


(2, 3)

In [24]:
np.r_['0, 3', [0, 1, 2], [3, 3, 3]]

array([[[0, 1, 2]],

       [[3, 3, 3]]])

In [25]:
print(np.array([0, 1, 2]).shape)
print(np.array([3, 3, 3]).shape)
np.r_['0, 3', [0, 1, 2], [3, 3, 3]].shape

(3,)
(3,)


(2, 1, 3)

In [26]:
np.r_['0, 2, 0', [0, 1, 2], [3, 3, 3]]

array([[0],
       [1],
       [2],
       [3],
       [3],
       [3]])

In [27]:
np.r_['0, 2, 0', [0, 1, 2], [3, 3, 3]].shape

(6, 1)

In [28]:
np.r_['0, 3, 0', [0, 1, 2], [3, 3, 3]]

array([[[0]],

       [[1]],

       [[2]],

       [[3]],

       [[3]],

       [[3]]])

In [29]:
np.r_['0, 3, 0', [0, 1, 2], [3, 3, 3]].shape

(6, 1, 1)

## 透過切片建立陣列

In [30]:
np.r_[0:10]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
np.r_[:10]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [32]:
np.r_[:10:2]

array([0, 2, 4, 6, 8])

In [34]:
np.r_[10:0:-1]

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [35]:
np.r_[0:10, 0 , 4, np.array([3, 3])]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 4, 3, 3])

## 傳入'r', 'c' 建立matrix


In [37]:
a = np.array([1, 4, 6])
b = np.array([2, 2, 2])
np.r_['r', a, b]

matrix([[1, 4, 6, 2, 2, 2]])

In [38]:
np.r_['c', a, b]

matrix([[1],
        [4],
        [6],
        [2],
        [2],
        [2]])

In [39]:
c = np.ones((4, 5))
d = np.zeros((2, 5))
np.r_['r', c, d]

matrix([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [40]:
np.r_['c', c, d]

matrix([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

## np.c_ 是針對最後一軸合併

In [41]:
a = np.ones((3, 2))
b = np.zeros((3, 3))
np.c_[a, b]

array([[1., 1., 0., 0., 0.],
       [1., 1., 0., 0., 0.],
       [1., 1., 0., 0., 0.]])

In [42]:
c = np.zeros(3)
np.c_[a, c]

array([[1., 1., 0.],
       [1., 1., 0.],
       [1., 1., 0.]])