## 只有支援2D

In [1]:
import numpy as np 
a = np.random.randn(3, 4)
np.savetxt('sample.txt', a)
b = np.loadtxt('sample.txt')

In [2]:
a

array([[ 2.2430409 ,  1.70001563,  0.46601654, -2.0351747 ],
       [-1.26746433,  2.64911222, -0.27894091, -0.33601928],
       [ 1.01701533, -0.04909772, -0.61524373,  1.52680942]])

In [3]:
b

array([[ 2.2430409 ,  1.70001563,  0.46601654, -2.0351747 ],
       [-1.26746433,  2.64911222, -0.27894091, -0.33601928],
       [ 1.01701533, -0.04909772, -0.61524373,  1.52680942]])

In [4]:
np.savetxt('sample.csv', a)
c = np.loadtxt('sample.csv')
c

array([[ 2.2430409 ,  1.70001563,  0.46601654, -2.0351747 ],
       [-1.26746433,  2.64911222, -0.27894091, -0.33601928],
       [ 1.01701533, -0.04909772, -0.61524373,  1.52680942]])

## 儲存時，變更分隔符號

In [5]:
np.savetxt('sample2.txt', a, delimiter=',')

In [6]:
e = np.loadtxt('sample2.txt')

ValueError: could not convert string to float: '2.243040900674712734e+00,1.700015633174296603e+00,4.660165418261326686e-01,-2.035174696877028122e+00'

In [22]:
e = np.loadtxt('sample2.txt', delimiter=',')
e

array([[ 2.2430409 ,  1.70001563,  0.46601654, -2.0351747 ],
       [-1.26746433,  2.64911222, -0.27894091, -0.33601928],
       [ 1.01701533, -0.04909772, -0.61524373,  1.52680942]])

## 儲存時，變更顯示格式

In [23]:
np.savetxt('sample3.txt', a ,fmt='%.2e')

In [24]:
np.savetxt('sample4.txt', a ,fmt='%.2f')

## 儲存時，加入註解

In [25]:
np.savetxt('sample5.txt', a ,fmt='%.2e',header='this is a header', footer='this is a footer')

In [26]:
np.savetxt('sample6.txt', a ,fmt='%.2e',header='this is a header', footer='this is a footer', comments='>>>')
f = np.loadtxt('sample6.txt', comments='>>>')
f

array([[ 2.24  ,  1.7   ,  0.466 , -2.04  ],
       [-1.27  ,  2.65  , -0.279 , -0.336 ],
       [ 1.02  , -0.0491, -0.615 ,  1.53  ]])

## 讀取特定行列

In [27]:
np.loadtxt('sample4.txt')

array([[ 2.24,  1.7 ,  0.47, -2.04],
       [-1.27,  2.65, -0.28, -0.34],
       [ 1.02, -0.05, -0.62,  1.53]])

In [28]:
np.loadtxt('sample4.txt', usecols=(0,2))

array([[ 2.24,  0.47],
       [-1.27, -0.28],
       [ 1.02, -0.62]])

In [29]:
np.loadtxt('sample4.txt', skiprows=1)


array([[-1.27,  2.65, -0.28, -0.34],
       [ 1.02, -0.05, -0.62,  1.53]])

In [30]:
np.loadtxt('foo.csv', dtype=[('age', 'i8'), ('gender', 'S10'), ('tall', 'i8'), ('license', 'S10')])

ValueError: invalid literal for int() with base 10: '18,female,154.1,No'

## dtpye

In [31]:
np.loadtxt("foo.csv", dtype=[('1','i8'),('2','S10'),('3','f8'),('4','S10')], delimiter=',')

array([(18, b'female', 154.1, b'No'), (21, b'male', 172.3, b'Yes'),
       (22, b'female', 160.8, b'Yes'), (23, b'male', 180.1, b'Yes'),
       (25, b'female', 145. , b'No')],
      dtype=[('1', '<i8'), ('2', 'S10'), ('3', '<f8'), ('4', 'S10')])

In [ ]:
np.loadtxt("foo.csv", dtype=[('1','i8'),('2','S10'),('3','f8'),('4','S10')], delimiter=',', unpack=True)

In [32]:
age, gender, tall, license_ =  np.loadtxt("foo.csv", dtype=[('1','i8'),('2','S10'),('3','f8'),('4','S10')], delimiter=',', unpack=True)

In [33]:
age

array([18, 21, 22, 23, 25], dtype=int64)

## Converters

In [36]:
def driver_license(str):
    if str == b'Yes' : return 1
    else: return -1
def gender(str):
    if str == b'male': return 1
    else: return -1
np.loadtxt("foo.csv", delimiter=',', converters={1: gender,3: driver_license})    

array([[ 18. ,  -1. , 154.1,  -1. ],
       [ 21. ,   1. , 172.3,   1. ],
       [ 22. ,  -1. , 160.8,   1. ],
       [ 23. ,   1. , 180.1,   1. ],
       [ 25. ,  -1. , 145. ,  -1. ]])