## np.arary()

In [37]:
import numpy as np 

a = np.array([1,2,3])
print(type(a))
print(a)

<class 'numpy.ndarray'>
[1 2 3]


In [38]:
a * 3

array([3, 6, 9])

In [39]:
a + 3

array([4, 5, 6])

In [40]:
b = np.array([2,2,0])
print(a + b)
print(a / b)
print(a * b)

[3 4 3]
[0.5 1.  inf]
[2 4 0]


## np.arange()

In [41]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [42]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

## np.linspace()

In [43]:
np.linspace(0,10,15)

array([ 0.        ,  0.71428571,  1.42857143,  2.14285714,  2.85714286,
        3.57142857,  4.28571429,  5.        ,  5.71428571,  6.42857143,
        7.14285714,  7.85714286,  8.57142857,  9.28571429, 10.        ])

## 二緯陣列

In [44]:
c = np.array([[1,2,3],[4,5,6]])
c

array([[1, 2, 3],
       [4, 5, 6]])

In [45]:
c.shape

(2, 3)

## 三緯陣列

In [46]:
d = np.array([[[1,2,3],[4,5,6],
               [7,8,9],[10,11,12]],
              [[13,14,15],[16,17,18],
              [19,20,21],[22,23,24]]])
d

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18],
        [19, 20, 21],
        [22, 23, 24]]])

In [47]:
d.shape

(2, 4, 3)

## reshape()

In [48]:
c.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [49]:
c.reshape(6,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])