In [7]:
import numpy as np
a = np.array([1,2,3])
print(type(a))
print(a)
print(a.data)
print(a.dtype)

<class 'numpy.ndarray'>
[1 2 3]
int32


In [8]:
b = np.array([[1,2,3],[4,5,6]])
print(b)
print(b.T)

[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]


## axis(軸)  dimension(維度)

In [9]:
print(b.shape)
print(b.ndim)

(2, 3)
2


In [10]:
a = np.array([[1,2],[3,4],[5,6]])
print(a)
print(a.shape)

[[1 2]
 [3 4]
 [5 6]]
(3, 2)


In [11]:
b = np.array([a,a])
print(b)

[[[1 2]
  [3 4]
  [5 6]]

 [[1 2]
  [3 4]
  [5 6]]]


In [12]:
b.sum(axis=0)

array([[ 2,  4],
       [ 6,  8],
       [10, 12]])

In [13]:
b.sum(axis=1)

array([[ 9, 12],
       [ 9, 12]])

In [14]:
b.sum(axis=2)

array([[ 3,  7, 11],
       [ 3,  7, 11]])

## dtype

In [15]:
import numpy as np
a = np.array([0,1,2])
a.dtype 

dtype('int32')

In [19]:
b= np.array([3,4,5],dtype='float')
print(b.dtype)
print(b)

float64
[3. 4. 5.]


In [20]:
e = np.array([3.5,-22,4.3],dtype='int')
e

array([  3, -22,   4])

In [21]:
f = np.array([0, 3, 0, -1],dtype='bool')
f

array([False,  True, False,  True])