In [1]:
import numpy as np 

a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [2]:
print(a[1:5])
print(a[2:8:2])
print(a[::-1])
print(a[:3])
print(a[4:])
print(a[:3],a[3:])
print(a[::2])
print(a[:])

[1 2 3 4]
[2 4 6]
[9 8 7 6 5 4 3 2 1 0]
[0 1 2]
[4 5 6 7 8 9]
[0 1 2] [3 4 5 6 7 8 9]
[0 2 4 6 8]
[0 1 2 3 4 5 6 7 8 9]


In [4]:
b = np.arange(20).reshape(4,5)
b

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [5]:
b[1:3, 2:4]

array([[ 7,  8],
       [12, 13]])

In [6]:
b[:2, 1:]

array([[1, 2, 3, 4],
       [6, 7, 8, 9]])

In [7]:
b[::2, :]

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14]])

In [8]:
b[:, ::2]

array([[ 0,  2,  4],
       [ 5,  7,  9],
       [10, 12, 14],
       [15, 17, 19]])

In [9]:
b[:, ::-1]

array([[ 4,  3,  2,  1,  0],
       [ 9,  8,  7,  6,  5],
       [14, 13, 12, 11, 10],
       [19, 18, 17, 16, 15]])

In [10]:
b[::-1, ::-1]

array([[19, 18, 17, 16, 15],
       [14, 13, 12, 11, 10],
       [ 9,  8,  7,  6,  5],
       [ 4,  3,  2,  1,  0]])