In [6]:
import numpy as np 

# Generate some random data
data = np.random.randn(2, 3)
print(data)
print(data * 10)
print(data + data)

# 每個陣列都有一個表示各緯度大小的元祖(shape)
print(data.shape)
print(data.dtype)

[[ 0.29547156  0.8961533  -0.11164185]
 [-0.66632842  0.9139601  -0.84813302]]
[[ 2.95471557  8.96153303 -1.11641853]
 [-6.66328419  9.13960104 -8.48133019]]
[[ 0.59094311  1.79230661 -0.22328371]
 [-1.33265684  1.82792021 -1.69626604]]
(2, 3)
float64


## Create ndarray

In [8]:
data1 = [6, 7.5, 8, 0, 1]
arr1 = np.array(data1)
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [9]:
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]
arr2 = np.array(data2)
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [15]:
# method (ndim & shape)
print(arr2.ndim)
print(arr2.shape)
print(arr2.dtype)

2
(2, 4)
int32
