### np.add()

In [13]:
import numpy as np 

a = np.array([0, 1, 2, 3, 4])
b = np.array([2, 4, 6, 8, 10])
print(a + b)
print(a + 4)
print(np.add(a, b))
print(np.add(a, 4))

[ 2  5  8 11 14]
[4 5 6 7 8]
[ 2  5  8 11 14]
[4 5 6 7 8]


### np.subtract()

In [14]:
print(a - b)
print(b - a)
print(a - 4)
print(np.subtract(a, b))
print(np.subtract(a, 4))

[-2 -3 -4 -5 -6]
[2 3 4 5 6]
[-4 -3 -2 -1  0]
[-2 -3 -4 -5 -6]
[-4 -3 -2 -1  0]


### np.multiply()

In [15]:
print(a * b)
print(a * 4)
print(np.multiply(a, b))
print(np.multiply(a, 4))

[ 0  4 12 24 40]
[ 0  4  8 12 16]
[ 0  4 12 24 40]
[ 0  4  8 12 16]


### np.divide()

In [16]:
print(a / b)
print(a / 4)
print(np.divide(a, b))
print(np.divide(a, 4))

[0.         0.25       0.33333333 0.375      0.4       ]
[0.   0.25 0.5  0.75 1.  ]
[0.         0.25       0.33333333 0.375      0.4       ]
[0.   0.25 0.5  0.75 1.  ]


### np.mod()

In [19]:
print(b)
print(b // 3)
print(b % 3)
print(np.mod(b, 3))

[ 2  4  6  8 10]
[0 1 2 2 3]
[2 1 0 2 1]
[2 1 0 2 1]
