In [3]:
import numpy as np 
print(np.power(2, 3))
print(2**3) 

8
8


In [7]:
a = np.arange(1, 11, 1)
b = np.array([1, 2, 1, 2, 1, 2, 1, 2, 1, 2])
print(a)
print(b)
print(np.power(a, b))
print(a ** b)

[ 1  2  3  4  5  6  7  8  9 10]
[1 2 1 2 1 2 1 2 1 2]
[  1   4   3  16   5  36   7  64   9 100]
[  1   4   3  16   5  36   7  64   9 100]


In [9]:
print(np.sqrt(2))
print(np.sqrt(a))

1.4142135623730951
[1.         1.41421356 1.73205081 2.         2.23606798 2.44948974
 2.64575131 2.82842712 3.         3.16227766]
