In [1]:
import numpy as np 
print(np.exp(1))
print(np.exp(2))
print(np.exp(0))

2.718281828459045
7.38905609893065
1.0


In [9]:
print(np.log(np.e))

a = np.array([1., 2., np.e**2, 10])
print(a)
print(np.log(a))
print(np.log1p(a))

b = np.array([1., 2., 4., 7])
print(b)
print(np.log2(b))

c = np.array([1., 10., 20., 100])
print(c)
print(np.log10(c))

1.0
[ 1.         2.         7.3890561 10.       ]
[0.         0.69314718 2.         2.30258509]
[0.69314718 1.09861229 2.12692801 2.39789527]
[1. 2. 4. 7.]
[0.         1.         2.         2.80735492]
[  1.  10.  20. 100.]
[0.      1.      1.30103 2.     ]


In [10]:
np.log(2) / np.log(4)

0.5

In [11]:
np.log(9) / np.log(3)

2.0